# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global.parameters]
stack_name = "fast-api-sam"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_NAMED_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "fast-api-sam"
region = "us-east-1"
parameter_overrides = "Environment=\"dev\" Version=\"0.0.1\""
image_repositories = ["ApiGatewayFunction=142069445226.dkr.ecr.us-east-1.amazonaws.com/fastapisamab395210/apigatewayfunction76b37ea6repo"]

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
